# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: abelomar <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/05 18:45:59 by abelomar          #+#    #+#              #
#    Updated: 2018/10/05 18:55:06 by abelomar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
all : $(NAME)
$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) ft_display_file.c
clean :
	rm -f *.o
fclean : clean
	rm -f $(NAME)
	
